# ----- REDIS CONFIG -----
INDEX_NAME: "doc-embeddings"
INDEX_PREFIX: "doc"
REDIS_HOST:  "localhost"
REDIS_PASSWORD: "" # default for passwordless Redis

# ----- SERVER PORT ----
REDIS_PORT: "6379"
SERVER_PORT: "8080"

# ---- OPENAI CONFIG -----
EMBEDDINGS_MODEL: "text-embedding-ada-002-2"
GENERATIVE_MODEL: "gpt-35-turbo"
EMBEDDING_DIMENSION: 1536
TEXT_EMBEDDING_CHUNK_SIZE: 200
DISTANCE_METRIC: "COSINE"
# This is the minimum cosine similarity score that a file must have with the search query to be considered relevant
# This is an arbitrary value, and you should vary/ remove this depending on the diversity of your dataset
COSINE_SIM_THRESHOLD: 0.1
MAX_TEXTS_TO_EMBED_BATCH_SIZE: 100
